# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20170727_0043'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
            ],
        ),
    ]
